@startuml

title Sequence Diagram - User Sign In / Sign Out

actor User
participant "SignIn.tsx" as React
participant "Auth0" as Auth0

User -> React: Clicks 'Sign In' Button
React -> User: Display Auth0 sign in form
User -> React: Inputs Email & Password / Signs In Using Google
React -> Auth0: Sends login data (POST /auth0 loginWithRedirect)
React -> Auth0: Verify user is authenticated
Auth0 -> React: Redirect User to Dashboard
React -> User: Dashboard is Rendered


alt Valid Credentials
    Auth0 -> React: Success (User Authenticated)
    React -> React: Navigate to Dashboard
    React -> User: User successfully signed in, Display Dashboard
end

alt Invalid Email
    Auth0 -> React: Invalid (User not Authenticated), Sign In Displayed
    React -> User : User Notified
end

alt Invalid Password
    Auth0 -> React: Invalid (User not Authenticated), Sign In Displayed
    React -> User : User Notified
end


== User Sign Out ==
User -> React: Clicks 'Sign Out' Button
React -> React: Clear session
React  -> Auth0: Logout User 
Auth0 -> React: Redirect to Home Page
React -> User: Home Page Displayed

@enduml